### ISSUE TITLE
Random scroll behavior issue when reloading the page

### ISSUE THREAD

**Issue by marcfilleul** [sgraewe/create-nuxt-tailwind-app#1]
Hi,

First of all, thank you for this great starter.

But I've come across a weird issue while using it.

When reloading a page, sometimes the scroll position is saved and sometimes not.
When relaoding several times, the scroll position will go back to top and then go back to the saved position.
It seems totally random but it happens a lot, only in production.

I'm using the latest version of Chrome in Windows.

Strangely enough, when hard reloading the page (CTRL+F5), the scroll position is always saved as it should.

Here is a simple page to test the issue:
[https://nuxt-tailwind-app-mfprod.netlify.com/](https://nuxt-tailwind-app-mfprod.netlify.com/)

It's a fresh `yarn create nuxt-tailwind-app` install with only some Lorem Ipsume added to index.vue to be able to test the scroll issue.

**Comment by marcfilleul** [comment]
I've made some tests with a basic create nuxt-app install.

I have the same issue when adding tailwindcss like this:

```
build: {
    /*
     ** PostCSS setup
     */
    postcss: {
      // Add plugin names as key and arguments as value
      // Disable a plugin by passing false as value
      plugins: {
        tailwindcss
      },
      // Change the postcss-preset-env settings
      preset: {
        stage: 0,
        autoprefixer: {
          cascade: false,
          grid: true
        }
      }
    },
    /*
     ** Extract CSS
     */
    extractCSS: true,
    /*
     ** You can extend webpack config here
     */
```

So it's not related to your settings or to purgecss.

**Comment by marcfilleul** [comment]
Finally, after another test with the classic create-nuxt-app and Tailwind option, I can confirm that the issue is not happening with the old way settings.

So it seems to be related to the new postcss plugin settings for tailwind css.

**Comment by marcfilleul** [comment]
Hi,
After several more tests, I've found the culprit !

The scroll behavior issue is related to "Extract CSS" !

By using postcss mode instead of webpack mode and removing Extract CSS, the issue disappear ;)

**Comment by sgraewe** [comment]
Sorry for the late response, I was on vacation.

Will have a look later and set postcss mode as default.
